"""empty message

Revision ID: 7dd71f1af063
Revises: 
Create Date: 2020-05-23 14:48:01.769844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd71f1af063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawledjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('pub_date', sa.String(length=255), nullable=True),
    sa.Column('end_date', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_city', sa.String(length=255), nullable=True),
    sa.Column('job_state', sa.String(length=255), nullable=True),
    sa.Column('job_country', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobpikrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('has_expired', sa.String(length=255), nullable=True),
    sa.Column('inferred_country', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('crawl_timestamp', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('inferred_city', sa.String(length=255), nullable=True),
    sa.Column('salary_offered', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('uniq_id', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('inferred_state', sa.String(length=255), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('cursor', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['marketplace_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('required_skill_one', sa.String(length=255), nullable=True),
    sa.Column('required_skill_two', sa.String(length=255), nullable=True),
    sa.Column('required_skill_three', sa.String(length=255), nullable=True),
    sa.Column('required_skill_four', sa.String(length=255), nullable=True),
    sa.Column('required_skill_five', sa.String(length=255), nullable=True),
    sa.Column('required_skill_six', sa.String(length=255), nullable=True),
    sa.Column('required_skill_seven', sa.String(length=255), nullable=True),
    sa.Column('required_skill_eight', sa.String(length=255), nullable=True),
    sa.Column('required_skill_nine', sa.String(length=255), nullable=True),
    sa.Column('required_skill_ten', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marketplace_carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('charge_id', sa.String(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('products_total', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.Column('order_discount', sa.Float(), nullable=True),
    sa.Column('order_pay_amount', sa.Float(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('price_currency_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.BigInteger(), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_orders_city'), 'marketplace_orders', ['city'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_country'), 'marketplace_orders', ['country'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_email'), 'marketplace_orders', ['email'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_first_name'), 'marketplace_orders', ['first_name'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_last_name'), 'marketplace_orders', ['last_name'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_mobile_phone'), 'marketplace_orders', ['mobile_phone'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_state'), 'marketplace_orders', ['state'], unique=False)
    op.create_index(op.f('ix_marketplace_orders_zip'), 'marketplace_orders', ['zip'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_currency_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('lead_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_shipping_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_name'), 'notifications', ['name'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('org_city', sa.String(length=255), nullable=True),
    sa.Column('org_state', sa.String(length=255), nullable=True),
    sa.Column('org_country', sa.String(length=255), nullable=True),
    sa.Column('org_website', sa.String(length=255), nullable=True),
    sa.Column('org_industry', sa.String(length=255), nullable=True),
    sa.Column('org_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('answers_level_idx', 'answers', ['level'], unique=False)
    op.create_index('answers_lft_idx', 'answers', ['lft'], unique=False)
    op.create_index('answers_rgt_idx', 'answers', ['rgt'], unique=False)
    op.create_index(op.f('ix_answers_body'), 'answers', ['body'], unique=False)
    op.create_index(op.f('ix_answers_timestamp'), 'answers', ['timestamp'], unique=False)
    op.create_table('entry_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('position_city', sa.String(length=255), nullable=True),
    sa.Column('position_state', sa.String(length=255), nullable=True),
    sa.Column('position_country', sa.String(length=255), nullable=True),
    sa.Column('required_skill_one', sa.String(length=255), nullable=True),
    sa.Column('required_skill_two', sa.String(length=255), nullable=True),
    sa.Column('required_skill_three', sa.String(length=255), nullable=True),
    sa.Column('required_skill_four', sa.String(length=255), nullable=True),
    sa.Column('required_skill_five', sa.String(length=255), nullable=True),
    sa.Column('required_skill_six', sa.String(length=255), nullable=True),
    sa.Column('required_skill_seven', sa.String(length=255), nullable=True),
    sa.Column('required_skill_eight', sa.String(length=255), nullable=True),
    sa.Column('required_skill_nine', sa.String(length=255), nullable=True),
    sa.Column('required_skill_ten', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_position_state'), 'jobs', ['position_state'], unique=False)
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_cart_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile_phone', sa.BigInteger(), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_cart_details_city'), 'marketplace_cart_details', ['city'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_country'), 'marketplace_cart_details', ['country'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_email'), 'marketplace_cart_details', ['email'], unique=True)
    op.create_index(op.f('ix_marketplace_cart_details_first_name'), 'marketplace_cart_details', ['first_name'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_last_name'), 'marketplace_cart_details', ['last_name'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_mobile_phone'), 'marketplace_cart_details', ['mobile_phone'], unique=True)
    op.create_index(op.f('ix_marketplace_cart_details_state'), 'marketplace_cart_details', ['state'], unique=False)
    op.create_index(op.f('ix_marketplace_cart_details_zip'), 'marketplace_cart_details', ['zip'], unique=False)
    op.create_table('marketplace_product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_seller_carts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('current_currency_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['marketplace_shipping_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_seller_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('current_currency_id', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['marketplace_shipping_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_shipping_method_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('price_currency_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_currency_id'], ['marketplace_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['marketplace_shipping_methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('post_privacy', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('image_filename', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('hotness', sa.Float(precision=15, asdecimal=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('promo_title', sa.String(length=255), nullable=True),
    sa.Column('promo_city', sa.String(length=255), nullable=True),
    sa.Column('promo_state', sa.String(length=255), nullable=True),
    sa.Column('promo_country', sa.String(length=255), nullable=True),
    sa.Column('requirement_one', sa.String(length=255), nullable=True),
    sa.Column('requirement_two', sa.String(length=255), nullable=True),
    sa.Column('requirement_three', sa.String(length=255), nullable=True),
    sa.Column('requirement_four', sa.String(length=255), nullable=True),
    sa.Column('requirement_five', sa.String(length=255), nullable=True),
    sa.Column('requirement_six', sa.String(length=255), nullable=True),
    sa.Column('requirement_seven', sa.String(length=255), nullable=True),
    sa.Column('requirement_eight', sa.String(length=255), nullable=True),
    sa.Column('requirement_nine', sa.String(length=255), nullable=True),
    sa.Column('requirement_ten', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_cart_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('seller_cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['marketplace_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_cart_id'], ['marketplace_seller_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('seller_order_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('current_total_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_seller_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_order_id'], ['marketplace_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('post_comments_level_idx', 'post_comments', ['level'], unique=False)
    op.create_index('post_comments_lft_idx', 'post_comments', ['lft'], unique=False)
    op.create_index('post_comments_rgt_idx', 'post_comments', ['rgt'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('extra_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_order_status_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('changed_from', sa.Integer(), nullable=True),
    sa.Column('changed_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['marketplace_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('area_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('invited_by', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('is_seller', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('mobile_phone', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('online', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('profession', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('recruiter_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('socket_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('summary_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('zip', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_area_code'), 'users', ['area_code'], unique=False)
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_mobile_phone'), 'users', ['mobile_phone'], unique=True)
    op.create_index(op.f('ix_users_profession'), 'users', ['profession'], unique=False)
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    op.create_index(op.f('ix_users_zip'), 'users', ['zip'], unique=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'users', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_users_zip'), table_name='users')
    op.drop_index(op.f('ix_users_state'), table_name='users')
    op.drop_index(op.f('ix_users_profession'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_phone'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_index(op.f('ix_users_area_code'), table_name='users')
    op.drop_column('users', 'zip')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'summary_text')
    op.drop_column('users', 'state')
    op.drop_column('users', 'socket_id')
    op.drop_column('users', 'recruiter_id')
    op.drop_column('users', 'profession')
    op.drop_column('users', 'online')
    op.drop_column('users', 'mobile_phone')
    op.drop_column('users', 'last_message_read_time')
    op.drop_column('users', 'is_seller')
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'area_code')
    op.drop_table('promo_submissions')
    op.drop_table('marketplace_order_status_changes')
    op.drop_table('job_applications')
    op.drop_table('comment_upvotes')
    op.drop_table('application_extras')
    op.drop_table('submissions')
    op.drop_table('post_upvotes')
    op.drop_table('post_likes')
    op.drop_index('post_comments_rgt_idx', table_name='post_comments')
    op.drop_index('post_comments_lft_idx', table_name='post_comments')
    op.drop_index('post_comments_level_idx', table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_table('photos')
    op.drop_table('marketplace_order_items')
    op.drop_table('marketplace_cart_items')
    op.drop_table('applications')
    op.drop_table('promos')
    op.drop_table('posts')
    op.drop_table('org_staff')
    op.drop_table('marketplace_shipping_method_prices')
    op.drop_table('marketplace_seller_orders')
    op.drop_table('marketplace_seller_carts')
    op.drop_table('marketplace_product_categories')
    op.drop_index(op.f('ix_marketplace_cart_details_zip'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_state'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_mobile_phone'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_last_name'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_first_name'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_email'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_country'), table_name='marketplace_cart_details')
    op.drop_index(op.f('ix_marketplace_cart_details_city'), table_name='marketplace_cart_details')
    op.drop_table('marketplace_cart_details')
    op.drop_table('logos')
    op.drop_index(op.f('ix_jobs_position_state'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('entry_tags')
    op.drop_index(op.f('ix_answers_timestamp'), table_name='answers')
    op.drop_index(op.f('ix_answers_body'), table_name='answers')
    op.drop_index('answers_rgt_idx', table_name='answers')
    op.drop_index('answers_lft_idx', table_name='answers')
    op.drop_index('answers_level_idx', table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_name'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('marketplace_shipping_methods')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_marketplace_orders_zip'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_state'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_mobile_phone'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_last_name'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_first_name'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_email'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_country'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_city'), table_name='marketplace_orders')
    op.drop_table('marketplace_orders')
    op.drop_table('marketplace_carts')
    op.drop_table('interests')
    op.drop_table('followers')
    op.drop_table('extras')
    op.drop_table('contact_messages')
    op.drop_table('tags')
    op.drop_table('marketplace_settings')
    op.drop_table('marketplace_currency')
    op.drop_table('marketplace_categories')
    op.drop_table('jobpikrs')
    op.drop_table('crawledjobs')
    # ### end Alembic commands ###
